# Generated by Django 4.2.4 on 2023-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogpost_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='hashtags',
            field=models.ManyToManyField(related_name='blog_posts', to='home.hashtag'),
        ),
    ]
